<!DOCTYPE HTML>
<!--
    Retrospect by TEMPLATED
    templated.co @templatedco
    Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>
    <head>
        <title>Adventure Time</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
        <link rel="stylesheet" href="assets/stylesheets/main.css" />
        <!--[if lte IE 8]><link rel="stylesheet" href="assets/stylesheets/ie8.css" /><![endif]-->
        <!--[if lte IE 9]><link rel="stylesheet" href="assets/stylesheets/ie9.css" /><![endif]-->
    </head>
    <body >

        <!-- Header -->
            <header id="header" >
                <h1><a href="index.html">AdventureTime</a></h1>
                <a href="#nav">Menu</a>
            </header>

        <!-- Nav -->
            <nav id="nav">
                <ul class="links">
                    <li><a href="index.php">Home</a></li>
                    <!--Add here some usefull links (generated by php ) -->
                    <li><a href="index.php?action=error">Error</a></li>
                </ul>
                <?php 
                    if(isset($_SESSION['logged']) && $_SESSION['logged']){
                        echo "Hello ".$_SESSION['displayname'].

                        '
                    <form action="#" method="POST">
                        <ul class="actions">
                             <li><input type="hidden" value="logOff" name="action" id="action"/></li>
                            <li><input type="submit" value="Log Off" name="Log Off" id="Log Off" /></li>
                        </ul>
                    </form>';
                    }
                    else echo '
                <form action="#" method="POST">
                                <div class="6u 12u$(xsmall)">
                                    <input name="username" placeholder="Name" type="text" />
                                </div>
                                <div class="6u$ 12u$(xsmall)">
                                    <input name="password" placeholder="Email" type="password" />
                                </div>

                        <ul class="actions">
                            <li><input type="reset" class="alt" value="Reset" /></li>
                             <li><input type="hidden" value="connection" name="action" id="action"/></li>
                            <li><input type="submit" value="Log in" name="Log in" id="Log in" /></li>
                        </ul>
                    </form>'; 
            ?>
            </nav>

        <!-- Banner -->
            <section id="banner">
                <i class="icon fa-diamond"></i>
                <h2>This is our Blog website</h2>
                <p>Just wait for it, it's gonna be legen...DARY</p>
                <ul class="actions">
                    <li><a href="#" class="button big special">Learn More</a></li>
                </ul>
            </section>

